kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/alertmanager-multitenant

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v ./multitenant
- name: build
  pull: default
  image: bearstech/golang-dep
  commands:
  - cd /go/src/github.com/factorysh/alertmanager-multitenant
  - make -C demo
- name: proxy
  image: bearstech/debian
  detach: true
  environment:
    AM_ADDRESS: http://alertmanager:9093
    LISTEN_ADDRESS: 0.0.0.0:9000
    SIGNATURE: secret
  commands:
  - demo/bin/demo
- name: functionnal_test
  pull: default
  image: bearstech/debian-dev
  commands:
  - >
    curl -i
    -H "JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o"
    -H "Content-Type: application/json"
    -d '[{"labels": {"project": "test"}}]'
    proxy:9000/api/v2/alerts | grep 200

services:
- name: alertmanager
  image: prom/alertmanager
  volumes: [ "demo/alertmanager/":"/etc/alertmanager" ]
- name: mailhog
  image: mailhog/mailhog
