kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/alertmanager-multitenant

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v ./multitenant
- name: func_test
  pull: default
  image: docker/compose:1.24.1
  commands:
  - apt update && apt install -y make curl
  - sh start_demo.sh
