kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/alertmanager-multitenant

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v ./multitenant
- name: goss_bin
  pull: default
  image: bearstech/debian-dev
  volumes:
  - name: goss
    path: /goss
  commands:
  - mkdir -p /goss/bin
  - curl -o goss/bin/goss -L https://github.com/aelsabbahy/goss/releases/download/v${GOSS_VERSION}/goss-linux-amd64
  - chmod 755 goss/bin/goss
- name: functionnal_test
  pull: default
  image: bearstech/debian
  volumes:
  - name: goss
    path: /goss
  commands:
  - /goss/goss -g /goss/proxy_test.yaml validate --max-concurrent 4 --format documentation

services:
- name: alertmanager
  image: prom/alertmanager
  volumes:
  - name: alertmanager
    path: /etc/alertmanager/
- name: alertmanager
  image: mailhog/mailhog
- name: proxy
  image: bearstech/debian
  volumes:
  - name: proxy
    path: /app
  environment:
    AM_ADDRESS: http://alertmanager:9093
    LISTEN_ADDRESS: 0.0.0.0:9000
    SIGNATURE: secret


volumes:
- name: alertmanager
  host:
    path: ./demo/alertmanager/
- name: proxy
  host:
    path: ./demo/bin
- name: goss
  host:
    path: ./test_goss
