kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/alertmanager-multitenant

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v ./multitenant
- name: functional test
  commands:
  - go build -o main
  - `./main`
  - `curl -i \
   -H "JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o" \
   -H "Content-Type: application/json" \
   -d '[{"labels": {"project": "test"}}]' 0.0.0.0:9000/api/v2/alertscew | grep 502`
