version: "3"

services:
    alertmanager:
        image: prom/alertmanager
        ports:
            - "9093:9093"
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        restart: always
        depends_on:
            - mailhog

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

    demo:
        image: bearstech/debian
        environment:
            - AM_ADDRESS=http://alertmanager:9093
            - LISTEN_ADDRESS=0.0.0.0:9000
            - SIGNATURE=secret
        ports:
            - "9000:9000"
        volumes:
            - ./bin/:/app
        command:
            - "/app/demo"
        restart: always

    client:
        image: bearstech/debian
        volumes:
            - ./test_goss/bin:/goss
            - ../test_goss:/goss/conf
        working_dir: /goss
        command: >
            ./goss -g conf/proxy_test.yaml validate --max-concurrent 4 --format documentation
